apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-guestbook
spec:
  generators:
    - list:
        elements:
          - cluster: kubernetes.default.svc
            namespace: dev
            overlay: dev
          - cluster: kubernetes.default.svc
            namespace: staging
            overlay: staging
          - cluster: kubernetes.default.svc
            namespace: prod
            overlay: prod
  template:
    metadata:
      name: 'helm-guestbook-{{ overlay }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/trung-cao-30/argocd-application-set.git
        targetRevision: master
        path: 'overlays/{{ overlay }}'
      destination:
        server: 'https://{{ cluster }}'
        namespace: '{{ namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
