apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-guestbook
spec:
  generators:
    - list:
        elements:
          - cluster: kubernetes.default.svc
            namespace: dev
            env: dev
          - cluster: kubernetes.default.svc
            namespace: staging
            env: staging
          - cluster: kubernetes.default.svc
            namespace: prod
            env: prod
  template:
    metadata:
      name: 'helm-guestbook-{{ env }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/trung-cao-30/argocd-example-apps.git
        targetRevision: master
        path: ./helm-guestbook
        # helm:
        #   valueFiles:
        #   - '{{ env }}/values.yaml'
      destination:
        server: 'https://{{ cluster }}'
        namespace: '{{ namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
