apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: helm-guestbook
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/trung-cao-30/argocd-example-apps
  branch: master
